### PR TITLE
feat: solhint + solhint-plugin-prettier for linting

### PR DESCRIPTION
**Pull request by gg2001**
- Added `solhint` and `solhint-plugin-prettier`
- Bumped dependencies in `package.json`
- Renamed `prettier` and `solhint` scripts in `package.json`
- Added `.solhint.json` config file (adapted from https://github.com/paulrberg/solidity-template/blob/main/.solhint.json)

Im not sure if adding solhint is the best idea since it makes the node_modules folder more bloated, but I find it very useful. Would like to hear thoughts on adding this.

### CODE REVIEW

**Comment by transmissions11** [comment]
Wouldn’t this block using lint if the project violates a solhint rule? I think you need to use --fix in the solhint script to fix

**Comment by transmissions11** [comment]
this reminded me that we should probably have a separate lint-check and lint-fix pair of scripts to allow both fixing in development and checking for conformity in CI

**Comment by gg2001** [comment]
Makes sense, I just added --fix to the solhint script

I also added a yarn lint:check for just doing a check
The yarn lint by default does a fix

**Comment by transmissions11** [comment]
Nice! I think you can simplify the `:fix` scripts by just having them do like `yarn solhint -- --fix`

**Comment by gg2001** [comment]
Thanks! Looks like the `--` isn't necessary anymore so I just put it as `yarn solhint:check --fix`

Screen Shot 2021-09-25 at 2 35 16 pm

**Comment by transmissions11** [comment]
ah nice sorry im used to npm not yarn

**Comment by transmissions11** [comment]
can you simplify the prettier fix script too? otherwise lgtm

**Comment by gg2001** [comment]
Done!

**Review by transmissions11 — APPROVED** [review]

**Comment by gakonst** [comment]
LGTM. Thank you @gg2001 for the contribution and @transmissions11 for the PR reviews. Really appreciate it.

**Pull request merged**
